export enum FabricReducerAction {
    INIT_CANVAS = "INI_CANVAS",
    ADD_OBJECT_TO_LAYER = "ADD_OBJECT_TO_LAYER",
    UPDATE_OBJECT_TO_LAYER = "UPDATE_OBJECT_TO_LAYER",
    REMOVE_OBJECT_TO_LAYER = "REMOVE_OBJECT_TO_LAYER",
    CLEAR_ALL_LAYER = "CLEAR_ALL_LAYER",
}
