
export const CATEGORIES_QUERIES = {
    GET_CATEGORIES_COLLECTIONS: "GET_CATEGORIES_COLLECTIONS",
    GET_ALL_CATEGORIES: "GET_ALL_CATEGORIES",
    GET_CATEGORY_LIST: "GET_CATEGORY_LIST",

} as const;