import React from "react";

export enum PROPERTY_QUERY_KEY {
    LIST_IMMOBILIER_GESTION = "LIST_IMMOBILIER_GESTION",
    GET_PRESTIGE_PROPERTIES = "GET_PRESTIGE_PROPERTIES",
}

export enum USER_QUERY_KEY {
    USER_LOCATION_VENTES = "USER_LOCATION_VENTES",
    USER_PERQUISITIONS_WARRANT = "USER_PERQUISITIONS_WARRANT",
}
